server:
  port: 8088

---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order_manage
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order_manage
          uri: http://order_manage:8080
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080