server:
  port: 8088

---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order_manage
          uri: http://localhost:8081
          predicates:
            - Path=/orders/** 
        - id: bill_collection
          uri: http://localhost:8082
          predicates:
            - Path=/bills/** 
        - id: logistics_manage
          uri: http://localhost:8083
          predicates:
            - Path=/logistics/** 
        - id: inventory_manager
          uri: http://localhost:8084
          predicates:
            - Path=/inventories/** 
        - id: totalview
          uri: http://localhost:8085
          predicates:
            - Path=/totalview/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order_manage
          uri: http://order_manage:8080
          predicates:
            - Path=/orders/** 
        - id: bill_collection
          uri: http://bill_collection:8080
          predicates:
            - Path=/bills/** 
        - id: logistics_manage
          uri: http://logistics_manage:8080
          predicates:
            - Path=/logistics/** 
        - id: inventory_manager
          uri: http://inventory_manager:8080
          predicates:
            - Path=/inventories/** 
        - id: totalview
          uri: http://totalview:8080
          predicates:
            - Path=/totalview/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080