server:
  port: 8088

---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rentalrequest
          uri: http://localhost:8081/rentalRequest
          predicates:
            - Path=/rentalRequest/** 
        - id: orderms
          uri: http://localhost:8081/orders
          predicates:
            - Path=/orders/** 
        - id: rentalcancel
          uri: http://localhost:8081/rentalCancel
          predicates:
            - Path=/rentalCancel/** 
        - id: totalview
          uri: http://localhost:8085/totalViews
          predicates:
            - Path=/totalview/**  
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rentalrequest
          uri: http://order:8080/rentalRequest
          predicates:
            - Path=/rentalRequest/** 
        - id: orderms
          uri: http://ordermanager:8080/orders
          predicates:
            - Path=/orders/** 
        - id: rentalcancel
          uri: http://order:8080/rentalCancel
          predicates:
            - Path=/rentalCancel/** 
        - id: totalview
          uri: http://totalview:8080/totalViews
          predicates:
            - Path=/totalView/**             
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080