server:
  port: 8088

---
spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: rentalRequest
          uri: http://localhost:8081/rentalRequest
          predicates:
            - Path=/rentalRequest/** 
        - id: orderms
          uri: http://localhost:8081/orders
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---
spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: rentalRequest
          uri: http://orders:8080/rentalRequest
          predicates:
            - Path=/rentalRequest/** 
        - id: orderms
          uri: http://orders:8080/orders
          predicates:
            - Path=/orders/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080